### ISSUE TITLE
Scrape all reviews for all nano drugs from drugs.com

### ISSUE THREAD

**Issue by jvargas2** [NanoNLP/medinify#34]
Use the new DrugsScraper() to scrape all of the reviews for the nano drugs and their non-nano versions. https://docs.google.com/spreadsheets/d/1CxiYFOulPbxJXJB_662KvuZKDVcWUHGGSVOPb7zbQAY/edit#gid=729608836

Add to the Google Drive when they're ready. https://drive.google.com/open?id=1xtpE1VBbz8GS7LAwsaV2V9M20gpQuN1l

**Comment by nrhwest** [comment]
Closing this issues because I've found no reviews on any of the nano drugs listed on the Nanomedicines Google sheet
