### ISSUE TITLE
Add Random Forest classifier to package

### ISSUE THREAD

**Issue by nrhwest** [NanoNLP/medinify#61]
You may read this file to read and understand how the random forest works in code, but I'd recommend reading the code in tandem with this URL explaining how the algorithm actually works conceptually.

Code: [random_forest.zip](https://github.com/NanoNLP/medinify/files/2823103/random_forest.zip)
Link: [https://towardsdatascience.com/the-random-forest-algorithm-d457d499ffcd](url)

Also, take note that code is not using k-fold cross validation.

**Comment by jvargas2** [comment]
Closed by PR #89
